### ISSUE TITLE
  Jekyll Feed: Generating feed for posts      Build Warning: Layout 'home' requested in index.md does not exist.                     done in 0.364 seconds.

### ISSUE THREAD

**Issue by 873578156** [b2a3e8/jekyll-theme-console#1]
Jekyll Feed: Generating feed for posts
     Build Warning: Layout 'home' requested in index.md does not exist.
                    done in 0.364 seconds.

**Comment by b2a3e8** [comment]
There is now a home layout available, introduced in version 0.3.0. Please use latest version of the theme (0.3.3):
`bundle update jekyll-theme-console`
