### ISSUE TITLE
Markdown or HTML images in posts

### ISSUE THREAD

**Issue by nothingAD** [b2a3e8/jekyll-theme-console#15]
Hey there,
i'm having some trouble linking images in my blogposts. At least it looks like github won't load the images. 

here is what i've tried so far 
`<img src="/content/january/df_map.png" alt="">`
`<img src="https://github.com/nothingAD/nothingAD.github.io/blob/master/files/dream1.PNG" alt=""/>`
`![](../files/dream1.PNG)`

Is there something missing? 
Best regards!

**Comment by b2a3e8** [comment]
Hi David,
Try this:
`![](/files/dream1.PNG)`

**Comment by nothingAD** [comment]
Hey somehow this worked. Thank you for your tip, i'm closing this issue.
`<img src="/content/january/df_map.PNG">`
