### ISSUE TITLE
adding a menu in header to show a list of posts and not just one markdown file

### ISSUE THREAD

**Issue by amansingh9097** [b2a3e8/jekyll-theme-console#17]
Hi,
First of all, thank you so much for this theme. I just love it!

Is it possible to have a menu along side the `/`, `/peter`, `/about` and `/contact` that would say `/blog` wherein one could list out a number of markdown files just as in the index page showing a list of posts?

Thanks,
Aman

**Comment by b2a3e8** [comment]
Hi Aman,

The theme doesn't provide a built-in secondary-menu. Maybe I can inspire you with some possible solutions:
- You could create a new page which is based on the layout "home". If you do that, you will get automatically a list of all your posts. That's not a secondary menu, but it may feels like a sub-menu and would be a very easy solution.
- You could fork this theme and modify it to create your own custom theme. You would want to change [_includes/header.html](https://github.com/b2a3e8/jekyll-theme-console/blob/master/_includes/header.html) and [_sass/base.scss](https://github.com/b2a3e8/jekyll-theme-console/blob/master/_sass/base.scss#L55). If you know html, css and jekyll a little, it is easy to add a secondary-menu or a dropdown-sub-menu or whatever... If you don't know html, css & jekyll don't be afraid to learn it! You're welcome to submit a pull-request with your changes if you think your solution is useful for others too.

I hope I could answer your question and help you with your request. Don't hesitate to ask if you need more assistance.

Cheers!

**Comment by thenishkarshagarwal** [comment]
@b2a3e8 
I have to deal with something similar; 

actually wanted to link the "posts" into the "/blog/" permalink instead of "/" {index.md};
but I am unable to do so, and the only option left is to manually link them into the blog.md file. 
`thenishkarshagarwal.github.io`

hope you can help me with the same.

**Comment by b2a3e8** [comment]
Hi @thenishkarshagarwal 
Just use the home layout.
```
---
title: /blog
layout: home
permalink: /blog
---
```

**Comment by thenishkarshagarwal** [comment]
I'm really sorry, I forgot to give you the incomplete details.
I already did that, but IDK why it didn't work. 
https://github.com/thenishkarshagarwal/thenishkarshagarwal.github.io/blob/main/blog.md

also changed index.md to "page".
@b2a3e8

**Comment by b2a3e8** [comment]
Ok so you're doing that right but I think your post is not generated by jekyll. Check this page: https://stackoverflow.com/questions/30625044/jekyll-post-not-generated
If that doesn't help I would clone the repo on your machine and debug local.. But I'm pretty sure above link helps, especially the part of the naming convention of your files (your post file name doesn't contain a date...

**Comment by thenishkarshagarwal** [comment]
`your post file name doesn't contain a date`

damn, I'm a fool. I noticed it earlier, but forgot to apply it. 
a lot thanks for helping me out. this now works.

![image](https://user-images.githubusercontent.com/68452918/96034117-ae6d5100-0e7e-11eb-8b1d-bef6bb2a18f5.png)

**Comment by thenishkarshagarwal** [comment]
right now, the "test post"'s URL looks like this : 
`https://thenishkarshagarwal.github.io/2020/11/15/test-post.html`

how can I change this to something like this : 
`https://thenishkarshagarwal.github.io/blog/test-post.html`

**without manually linking it in the blog.md file?**

**Comment by b2a3e8** [comment]
Thats a generic jekyll question - please ask Google.

**Comment by thenishkarshagarwal** [comment]
yea, alright. thanks a lot for your help, pal.
