### ISSUE TITLE
Margin bottom on paragraphs?

### ISSUE THREAD

**Issue by atugushev** [b2a3e8/jekyll-theme-console#21]
`p {marin-bottom: 15px}` looks good

<img width="628" alt="image" src="https://user-images.githubusercontent.com/7377671/87879164-37592580-ca13-11ea-895b-c0e4fb4302ed.png">

<img width="620" alt="image" src="https://user-images.githubusercontent.com/7377671/87879153-201a3800-ca13-11ea-8cda-2663fea4e2f8.png">

<img width="633" alt="image" src="https://user-images.githubusercontent.com/7377671/87879139-02e56980-ca13-11ea-9947-0f190ef08a6c.png">

**Comment by foxmean** [comment]
Couldn't agree more.

**Comment by yuri1969** [comment]
Yes, this margin improves readability tremendously 👍

**Comment by b2a3e8** [comment]
hi @atugushev 
thanks for the proposal! i implemented it and published it in [v0.3.11](https://rubygems.org/gems/jekyll-theme-console/versions/0.3.11).
cheers, b2a3e8
