### ISSUE TITLE
SEO error

### ISSUE THREAD

**Issue by flamendless** [b2a3e8/jekyll-theme-console#22]
Hi, after doing `bundle update` and the running `bundle exec jekyll serve` I get this error:
`Liquid Exception: Liquid syntax error (../_includes/head.html line 6): Unknown tag 'seo' included in ../_layouts/default.html`

**Comment by b2a3e8** [comment]
do you have a gemfile containing `gem 'jekyll-seo-tag'` and a _config.yml containing the following lines?
```
plugins:
  - jekyll-seo-tag
```

**Comment by flamendless** [comment]
Yes i have that

**Comment by bbry4n** [comment]
could you share the repo?

**Comment by b2a3e8** [comment]
can you share the repo?
