### ISSUE TITLE
[Question] Adding a page from a different folder on _config_yml

### ISSUE THREAD

**Issue by ghost** [b2a3e8/jekyll-theme-console#25]
Hi.
I really enjoy this project. Keep it up!
I have this question. I want to keep my repository clean, so I don't want to have everything in the root folder.
I would like to make an "index.md" page on the "guides" folder and put it on `header_pages` in `_config.yml`. But I can't get it working, I have tried writing something like this:
```YAML
header_pages:
  - home.md
  - about.md
  - contact.md
  - /guides/index.
```
but, after build, it was not on the header.
Do you know any workaround? 
Thanks.

**Comment by b2a3e8** [comment]
hi @nicknitewolf 
remove the leading / and specify the whole filename, just like this:
```yaml
header_pages:
  - guides/index.markdown
```
