### ISSUE TITLE
RSS Feed?

### ISSUE THREAD

**Issue by jakiisheep** [b2a3e8/jekyll-theme-console#26]
How can I make an RSS feed for my blog with this theme?

**Comment by b2a3e8** [comment]
I dont have any experience on that. But in my opinion this isn't a feature that's part of a theme - you can use other plugins like jekyll-feed for creating rss feeds.

**Comment by jakiisheep** [comment]
A lot of jekyll themes have RSS built in, e.g - [chirpy](https://github.com/cotes2020/jekyll-theme-chirpy) and mostly everyone who blogs wants a RSS feed.

I know this is a minimal theme, but I still think a RSS feed would be a good addition.

**Comment by b2a3e8** [comment]
Ok I see. I consider adding some of the features which chirpy has (like rss) to a new major version of this theme.
Please use 3rd party plugins for rss support in the mean time.
