### ISSUE TITLE
Is images supported by this theme?

### ISSUE THREAD

**Issue by BaRRaKudaRain** [b2a3e8/jekyll-theme-console#27]
Hey! Having some problems with images. They just don't display when I dropping them to the markdown file as links. Any suggestions?

**Comment by BaRRaKudaRain** [comment]
Tried the img html tag, but no luck!

**Comment by KaranJayachandra** [comment]
Hi, you need to specify the links using the base url as well. It would look something like:

`<img src="{{site.url}}/assets/images/image.png" alt="Image">`

The variable `site.url` is specified in `_config.yml` file.

**Comment by b2a3e8** [comment]
Thanks @KaranJayachandra for helping out and solving the problem!
