### ISSUE TITLE
Couple of Nav Bar Questions

### ISSUE THREAD

**Issue by Lombardi** [b2a3e8/jekyll-theme-console#4]
- How do I make / edit / change the nav bar?
- Do I need to change the code to work on the nav bar?

**Comment by b2a3e8** [comment]
You don't need to change any code to get the navbar working. Following steps are required to setup and customize the navbar:
1. Make sure you define in your jekyll config (_config.yml) the header_pages like this:
   ```
   header_pages:
     - index.md
     - peter.md
     - about.md
     - contact.md
   ```

2. Make sure in all files referenced from the header_pages to set the title meta attribute, like in this example:
   ```
   ---
   layout: page
   title: /about
   permalink: /about/
   ---
   
   content here...
   ```


You can find the source code of the demo site (for an example) here: https://github.com/b2a3e8/jekyll-theme-console/tree/gh-pages

If you need further assistance, please provide a link to your repo.

**Comment by Lombardi** [comment]
Okay, I will try to work on this one day, currently working another project right now.
