### ISSUE TITLE
How to get the contact form to work?

### ISSUE THREAD

**Issue by dawsoneliasen** [b2a3e8/jekyll-theme-console#6]
I love the theme, thanks for making it! Is there an easy way to make the contact form functional with my email?

**Comment by b2a3e8** [comment]
It depends on how/where your site is hosted. If it is on github pages, you’ll need an extra form submission tool/service.
You can find some form submission tools on the official jekyll website: https://jekyllrb.com/resources/
There are some other hosting services which include a form submission tool like Netlify (https://netlify.com).
If you’re hosting on a service where you can run code on server side (like php) you could simply write your own script to process contact requests.

**Comment by dawsoneliasen** [comment]
Great, thanks so much for the quick response!
