### ISSUE TITLE
Support user preference for light or dark mode

### ISSUE THREAD

**Issue by schwigri** [b2a3e8/jekyll-theme-console#7]
I think it would be nice to utilize the CSS query `@media (prefers-color-scheme: dark)` to enable the dark theme when the user prefers it, but still allow the site owner to enforce one or the other. Would this be something you would be open to considering? I would love to work on it.

**Comment by b2a3e8** [comment]
That's a great idea!
I think it would be good to add a configuration option for this (e.g. `listen_for_clients_preferred_style`), so one can easily switch on or off this behaviour.
If `listen_for_clients_preferred_style` is set, the `style` option is only a fallback for old browsers and those who have no preference.
What do you think about that?

**Comment by b2a3e8** [comment]
#8 merged.
Thanks for your contribution!
