### ISSUE TITLE
Changes for the VI/Blind 

### ISSUE THREAD

**Issue by TheBlindHacker** [b2a3e8/jekyll-theme-console#9]
Hello, 

Some changes I am trying to make and can not figure it out. 
I was trying to find a way to change the background color to a slate / dark gray,  (think parrot terminal) 
Then also make the font just a little bigger  maybe 2 points.

**Comment by b2a3e8** [comment]
I updated the documentation: https://github.com/b2a3e8/jekyll-theme-console#customization
You can reopen the issue if you need more help regarding this.
